name: Build Plugin Jar

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Find built JARs
        id: find_jars
        run: |
          mkdir -p jars
          find . -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" -exec cp {} jars/ \;
          echo "JAR_COUNT=$(ls jars | wc -l)" >> $GITHUB_ENV

      - name: Upload plugin jars
        if: env.JAR_COUNT != '0'
        uses: actions/upload-artifact@v4
        with:
          name: PlotSquared-Jars
          path: jars/
